name: SysDVR-Client

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - Client/**
      - ClientGUI/**
      - Libs/**
      - ReleaseClient.bat
  pull_request:
    branches: [ master ]
    paths:
      - Client/**
      - ClientGUI/**
      - Libs/**
      - ReleaseClient.bat

jobs:
  build:
    # Must use windows-2019 as windows-latest doesn't have .net framework 4.5 needed to build the GUI
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: true
    # Download ffmpeg for windows builds
    - uses: robinraju/release-downloader@v1.3
      with:
        repository: "BtbN/FFmpeg-Builds"
        latest: true
        fileName: "ffmpeg-master-latest-win64-lgpl-shared.zip"
    # Download releases from my libwdi fork for CI builds of Wdi-simple.exe, it's needd to install the USB driver
    - uses: robinraju/release-downloader@v1.3
      with:
        repository: "exelix11/libwdi"
        latest: true
        fileName: "wdi-simple.zip"
    - name: Download SDL2 bins
      run: iwr https://www.libsdl.org/release/SDL2-2.0.22-win32-x64.zip -o SDL2.zip
    # SysDVR-Client uses .NET6
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
    # SysDVR-ClientGUI uses net framework
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Run build script
      run: .\ReleaseClient.bat
    - uses: actions/upload-artifact@v3
      with:
        name: SysDVR-Client
        path: Client.7z
