name: SysDVR-Client android

on:
  push:
    branches: [ "6.0" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.x
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build client native lib
      run: |
        cd ./Client/Platform/Android
        ln -s ../Resources/resources app/src/main/assets
        chmod +x buildbinaries.sh
        ./buildbinaries.sh
    - name: Extract keystore from secrets
      run: |
        echo ${{ secrets.ANDROID_CI_CERT }} | base64 -d > /tmp/CI.jks
    - name: Configure cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/Client/Platform/Android/.gradle
          ${{ github.workspace }}/Client/Platform/Android/app/build
        key: gradle-cache
        restore-keys: gradle-cache
    - name: Build app with gradle
      run: |
        cd ./Client/Platform/Android
        ./gradlew assembleRelease
      env: 
        ANDROID_CI_KEY: ${{ secrets.ANDROID_CI_KEY }}
    - uses: actions/upload-artifact@v3
      with:
        name: SysDVR-Client
        path: ./Client/Platform/Android/app/build/outputs/apk/release/app-release.apk
